name: pest

on:
    push:

jobs:
    pest:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [8.1, 8.0, 7.4]
                laravel: [9.*, 8.*, 7.*]
                dependency-version: [prefer-lowest, prefer-stable]
                exclude:
                    - laravel: 9.*
                      php: 7.4
        timeout-minutes: 5
        env:
            GITHUB_SPONSORS_TOKEN: ${{ secrets.GH_SPONSORS_TOKEN }}
        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, mbstring, zip, pcntl, intl
            - run: |
                  composer require --dev "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
                  composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction
            - run: vendor/bin/pest
