name: pest

on:
    push:

jobs:
    pest:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [8.2, 8.1, 8.0, 7.4]
                laravel: [10.*, 9.*, 8.*, 7.*]
                dependency-version: [prefer-lowest, prefer-stable]
                exclude:
                    - laravel: 9.*
                      php: 7.4
                    - laravel: 10.*
                      php: [8.0, 7.4]
                include:
                    - laravel: 10.*
                      testbench: ^8.0
                      pest: ^1.0
                    - laravel: 9.*
                      testbench: ^7.0
                      pest: ^1.0
                    - laravel: 8.*
                      testbench: ^6.0
                      pest: ^1.0
                    - laravel: 7.*
                      testbench: ^5.0
                      pest: ^1.0
        timeout-minutes: 5
        env:
            GITHUB_SPONSORS_TOKEN: ${{ secrets.GH_SPONSORS_TOKEN }}

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, mbstring, zip, pcntl, intl
                  coverage: none

            - name: Install Dependencies
              run: |
                  composer require --dev "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "pestphp/pest:${{ matrix.pest }}" "pestphp/pest-plugin-laravel:${{ matrix.pest }}" --no-interaction --no-update
                  composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

            - name: Execute Tests
              run: vendor/bin/pest
